# Site settings
title: Kişisel Web Sayfam
general_email: ozmen.muhammet@outlook.com
academic_email: muhammetozmen.mdbf21@iste.edu.tr

description: > # this means to ignore newlines until "baseurl:"
  Kendi yaptıklarımı yazmak, belgelemek ve saklamak adına oluşturduğum websitem.

#baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://muhammetozmen.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: muhammetozmen
linkedin_username: muhammetozmen
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title